import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/workspace/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="ubh0bClFx-hRPKMuLcVtu-g8qhyf54qYg7lwBZP5ukc"
      />
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
